workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: '3.24.0'
      groups:
        - keystore_credentials
      vars:
        FLAVOR: "production"
        APP_ID: "com.driveclone.drive_clone"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - mayur123roger@gmail.com
        notify:
          success: true
          failure: true

